version: '3.7'

services:
  djangoapp:
    restart: always
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
    networks:
      - nginx_network
      - database1_network
    depends_on: 
      - database1

  nginx:
    image: nginx:1.17
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    env_file:
      - config/db/database1_env
    networks: 
      - database1_network
    volumes:
      - ./db/data:/var/lib/mysql

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume: 
  static_volume:
  media_volume:  