# Generated by Django 3.0.2 on 2020-01-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder_rules', '0002_group_rule_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_groups', to='finder_rules.Group'),
        ),
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_groups', to='finder_rules.Group'),
        ),
    ]
